version: 2.1
workflows:
  version: 2
  gh-pages-build:
    jobs:
      - build-site:
        filters:
          branches:
            only: update/travis-to-circle-ci
      - deploy-site:
        filters:
          branches:
            only: update/travis-to-circle-ci
jobs:
  build-site:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            echo "Hello, World"
            npm install
            npm run build-prod
  deploy-site:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            echo "Deployment Step"