version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
    # Primary container image where all steps run.
     - image: cimg/base:current 
    steps:
      - checkout
      - run: echo "this is the build job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
