version: 2.1
executors:
  mm-default-executor:
    docker:
      - image: cimg/node:lts
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/MissingMaps/partners/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  simple-echo:

    executor: mm-default-executor
    steps:
      - checkout
      - run: |
          echo Hello, World!

workflows:
  my-custom-workflow:
    jobs:
      - simple-echo
