version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-deploy:
    docker:
    # Primary container image where all steps run.
      - image: ruby-2.7.4
    steps:
      - checkout
      - build_node_v8_nvm
      - install_dependencies ## install , git, g++, any other deps needed
      - chmod run_deploy_script
      - npm install
      - npm run build-prod
      - run_deploy_script

# Orchestrate our job run sequence
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-deploy
